### ISSUE TITLE
Cannot find field from parent interface

### ISSUE THREAD

**Issue by yukchan** [graphql-java-kickstart/graphql-java-tools#188]
a FieldResolverError is thrown when the field is defined at parent interface

	at com.coxautodev.graphql.tools.FieldResolverScanner.missingFieldResolver(FieldResolverScanner.kt:55)
	at com.coxautodev.graphql.tools.FieldResolverScanner.findFieldResolver(FieldResolverScanner.kt:46)
	at com.coxautodev.graphql.tools.SchemaClassScanner.scanResolverInfoForPotentialMatches(SchemaClassScanner.kt:231)

**Comment by yukchan** [comment]
I guess getAllMethod should get the methods from interfaces as well:

internal class FieldResolverScanner(val options: SchemaParserOptions) {

    private val allowedLastArgumentTypes = listOfNotNull(DataFetchingEnvironment::class.java, options.contextClass)

    companion object {
        private val log = LoggerFactory.getLogger(FieldResolverScanner::class.java)

        fun getAllMethods(type: JavaType) =
                (type.unwrap().declaredMethods.toList()
                        + ClassUtils.getAllInterfaces(type.unwrap()).flatMap { it.methods.toList() }
                        + ClassUtils.getAllSuperclasses(type.unwrap()).flatMap { it.methods.toList() })
                        .asSequence()
                        .filter { !it.isSynthetic }
                        .filter { !Modifier.isPrivate(it.modifiers) }
                        // discard any methods that are coming off the root of the class hierarchy
                        // to avoid issues with duplicate method declarations
                        .filter { it.declaringClass != Object::class.java }
                        .toList()
    }

**Comment by yukchan** [comment]
It is at line 24 of FieldResolverScanner.kt

Consider the following case:
 public interface A {  int getX(); }
 public interface B extends A {  int getY(); }

If we define B in graphql schema, the library cannot read getX() from interface A and throw 

type A {
  x: Int
  y: Int
}
