### ISSUE TITLE
Kotlin Sequence test error Cloning 5.5.1

### ISSUE THREAD

**Issue by Salrandin** [graphql-java-kickstart/graphql-java-tools#243]
Hi,

Thanks for all the hard work keeping graphql-java-tools updated with the latest Graphql-java.

I am trying to clone the current latest version (5.5.1) which uses Graphql-java 11.
After adding all the necessary dependencies from the pom.xml I am finding this issue when I try to build:
`
    [junit] Testsuite: com.coxautodev.graphql.tools.MethodFieldResolverDataFetcherTest
    [junit] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.487 sec
    [junit] 
    [junit] Testcase: data fetcher executes suspend function on coroutineContext defined by options(com.coxautodev.graphql.tools.MethodFieldResolverDataFetcherTest):	Caused an ERROR
    [junit] java.lang.NoSuchMethodError: kotlin.sequences.SequencesKt.sequence(Lkotlin/jvm/functions/Function2;)Lkotlin/sequences/Sequence;
    [junit] java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: kotlin.sequences.SequencesKt.sequence(Lkotlin/jvm/functions/Function2;)Lkotlin/sequences/Sequence;
    [junit] 	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
    [junit] 	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
    [junit] 	at com.coxautodev.graphql.tools.MethodFieldResolverDataFetcherTest.data fetcher executes suspend function on coroutineContext defined by options(MethodFieldResolverDataFetcherTest.kt:44)
    [junit] Caused by: java.lang.NoSuchMethodError: kotlin.sequences.SequencesKt.sequence(Lkotlin/jvm/functions/Function2;)Lkotlin/sequences/Sequence;
    [junit] 	at kotlinx.coroutines.JobSupport.getChildren(JobSupport.kt:845)
    [junit] 	at com.coxautodev.graphql.tools.MethodFieldResolverDataFetcherTest$data fetcher executes suspend function on coroutineContext defined by options$resolver$1.isActive(MethodFieldResolverDataFetcherTest.kt:37)
    [junit] 	at com.coxautodev.graphql.tools.MethodFieldResolverDataFetcherTest$data fetcher executes suspend function on coroutineContext defined by options$resolver$1MethodAccess.invoke(Unknown Source)
    [junit] 	at com.coxautodev.graphql.tools.MethodFieldResolverDataFetcher$get$1.invokeSuspend(MethodFieldResolver.kt:201)
    [junit] 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
    [junit] 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
    [junit] 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
    [junit] 	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
    [junit] 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
`

I am getting NoSuchMethodError from kotlin sequences.  I have these relevant dependencies:
`
            
            KotlinStdlib = 1.3.x;

            KotlinxCoroutinesJdk8 = 1.1.x;

            KotlinxCoroutinesReactive = 1.1.x;
`
Is there a dependency I am missing?

Seems to fail here: https://github.com/Kotlin/kotlinx.coroutines/blob/master/common/kotlinx-coroutines-core-common/src/JobSupport.kt#L845

Tried to find Sequence.kt as a dependency and found it here:
https://github.com/JetBrains/kotlin/blob/master/libraries/stdlib/src/kotlin/collections/Sequence.kt

Is this the right object?

**Comment by Salrandin** [comment]
Okay, this was a silly issue with having KotlinRuntimeJava8 as a dependency as well having conflicting Sequence objects.  Closing.
