### ISSUE TITLE
[Question] Implement schema interface in java

### ISSUE THREAD

**Issue by berlingoqc** [graphql-java-kickstart/graphql-java-tools#267]
I have defined an interface with a child class in my schema. I Have implement the interface in java as an Abstract Class but the FieldResolver is trying to find the child class field in the mother class
```
interface Projet {
  id: Int!
  noms: String!
  description: String!

  montantCible: Int!
  dateDebut: Date!
  dateFin: Date!

  type: TypeProject!

  detentions: [Detention!]
  clients: [Client!]
  extension: Extension!
}

type ProjetVoyage implements Projet{
  # parent type
  id: Int!
  noms: String!
  description: String!

  montantCible: Int!
  dateDebut: Date!
  dateFin: Date!

  type: TypeProject!

  detentions: [Detention!]
  clients: [Client!]
  extension: Extension!

  # my type

  destination: String
}
```

```
@Entity
@NoArgsConstructor
@Getter
@Setter
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
public abstract class Projet {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    Integer id = 0;
    String noms = "";
    String description = "";
    Integer montantCible = 0;

    LocalDate dateDebut = null;
    LocalDate dateFin = null;

    TypeProjet type = null;

    @OneToMany
    @LazyCollection(LazyCollectionOption.FALSE)
    @JoinColumn(name = "idDetention")
    List<Detention> detentions = null;

    @OneToMany
    @JoinColumn(name = "idClient")
    @LazyCollection(LazyCollectionOption.FALSE)
    List<Client> clients = null;

    @OneToOne
    Extension extension = null;

    public static Projet fromTypeProjet(TypeProjet typeProjet) {
        switch (typeProjet) {
            case VOYAGE:
                return new ProjetVoyage();
            case RENOVATION:
                return null;
        }
        return null;
    }


}
```

```
@NoArgsConstructor
@Getter
@Setter
public class ProjetVoyage extends Projet {
    String destination;
}
```

```
Caused by: com.coxautodev.graphql.tools.FieldResolverError: No method or field found as defined in schema <unknown>:47 with any of the following signatures (with or without one of [interface graphql.schema.DataFetchingEnvironment] as the last argument), in priority order:

  ca.wquintal.projet.model.Projet.destination()
  ca.wquintal.projet.model.Projet.getDestination()
  ca.wquintal.projet.model.Projet.destination
	at com.coxautodev.graphql.tools.FieldResolverScanner.missingFieldResolver(FieldResolverScanner.kt:58) ~[graphql-java-tools-5.5.2.jar:na]
	at com.coxautodev.graphql.tools.FieldResolverScanner.findFieldResolver(FieldResolverScanner.kt:49) ~[graphql-java-tools-5.5.2.jar:na]
	at com.coxautodev.graphql.tools.SchemaClassScanner.scanResolverInfoForPotentialMatches(SchemaClassScanner.kt:251) ~[graphql-java-tools-5.5.2.jar:na]
	at com.coxautodev.graphql.tools.SchemaClassScanner.scanQueueItemForPotentialMatches(SchemaClassScanner.kt:245) ~[graphql-java-tools-5.5.2.jar:na]
	at com.coxautodev.graphql.tools.SchemaClassScanner.scanQueue(SchemaClassScanner.kt:105) ~[graphql-java-tools-5.5.2.jar:na]
	at com.coxautodev.graphql.tools.SchemaClassScanner.scanForClasses(SchemaClassScanner.kt:83) ~[graphql-java-tools-5.5.2.jar:na]
	at com.coxautodev.graphql.tools.SchemaParserBuilder.scan(SchemaParserBuilder.kt:166) ~[graphql-java-tools-5.5.2.jar:na]
	at com.coxautodev.graphql.tools.SchemaParserBuilder.build(SchemaParserBuilder.kt:207) ~[graphql-java-tools-5.5.2.jar:na]
	at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration.schemaParser(GraphQLJavaToolsAutoConfiguration.java:98) ~[graphql-spring-boot-autoconfigure-5.7.3.jar:na]
	at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration$$EnhancerBySpringCGLIB$$402382b4.CGLIB$schemaParser$2(<generated>) ~[graphql-spring-boot-autoconfigure-5.7.3.jar:na]
	at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration$$EnhancerBySpringCGLIB$$402382b4$$FastClassBySpringCGLIB$$b4e1efa1.invoke(<generated>) ~[graphql-spring-boot-autoconfigure-5.7.3.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363) ~[spring-context-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration$$EnhancerBySpringCGLIB$$402382b4.schemaParser(<generated>) ~[graphql-spring-boot-autoconfigure-5.7.3.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	... 138 common frames omitted
```

**Comment by stieglma** [comment]
I think I had the same problem, which is that type hierarchies are not automatically detected by graphql, you manually have to specify how they should be handled, e.g. in my spring boot project I did something like that:

```java
    @Bean
    public SchemaParserDictionary schemaParserDictionary() {
        SchemaParserDictionary dict = new SchemaParserDictionary();
        dict.add("ProjetVoyage", ProjetVoyage.class);
        return dict;
    }
```
Adding the bean was totally enough. If you are constructing your Schema differently, then this might also be necessary somewhere else

**Comment by vojtapol** [comment]
This can be resolved by providing the types in the schema parser dictionary.
