### ISSUE TITLE
java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.ObjectMapper.setDefaultPropertyInclusion

### ISSUE THREAD

**Issue by luizvnasc** [graphql-java-kickstart/graphql-java-tools#271]
Hello, 

Trying to create a simple graphql query and a field query I got this issue:

`Error executing GraphQL request!: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.ObjectMapper.setDefaultPropertyInclusion(Lcom/fasterxml/jackson/annotation/JsonInclude$Include;)Lcom/fasterxml/jackson/databind/ObjectMapper;
	at graphql.servlet.GraphQLObjectMapper.getJacksonMapper(GraphQLObjectMapper.java:49)
	at graphql.servlet.GraphQLObjectMapper.getGraphQLRequestMapper(GraphQLObjectMapper.java:61)
	at graphql.servlet.GraphQLObjectMapper.readGraphQLRequest(GraphQLObjectMapper.java:65)
	at graphql.servlet.AbstractGraphQLHttpServlet.lambda$init$4(AbstractGraphQLHttpServlet.java:212)
	at graphql.servlet.AbstractGraphQLHttpServlet.doRequest(AbstractGraphQLHttpServlet.java:309)
	at graphql.servlet.AbstractGraphQLHttpServlet.doRequestAsync(AbstractGraphQLHttpServlet.java:300)
	at graphql.servlet.AbstractGraphQLHttpServlet.doPost(AbstractGraphQLHttpServlet.java:330)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
...
`

then I run the maven-enforcer-plugin plugin to find some dependecies conflict and found this:

> Dependency convergence error for com.fasterxml.jackson.core:jackson-annotations:2.9.8 paths to dependency are:
> +-br.com.graphql_test
>   +-com.graphql-java-kickstart:graphql-java-servlet:7.4.1
>     +-com.fasterxml.jackson.core:jackson-annotations:2.9.8
> and
> +-br.com.graphql_test
>   +-com.graphql-java-kickstart:graphql-java-servlet:7.4.1
>     +-com.fasterxml.jackson.core:jackson-databind:2.9.8
>       +-com.fasterxml.jackson.core:jackson-annotations:2.9.0
> and
> +-br.com.graphql_test
>   +-com.graphql-java-kickstart:graphql-java-tools:5.6.0
>     +-com.fasterxml.jackson.module:jackson-module-kotlin:2.9.8
>       +-com.fasterxml.jackson.core:jackson-annotations:2.9.0
> 

is there anything that I'm doing wrong?

**[EDIT 1]**
I don't know why but it is working now **BUT** this error always occurs in the first call to the query.

**Comment by luizvnasc** [comment]
Trying to use graphql-java without graphql-java-tools and got the same error.

**Comment by andriusvisk** [comment]
Try running with java command line parameter "-verbose:class" - in my case it was an old version of Wildfly app server, whick was loading an old jackson-databind jar file

**Comment by luizvnasc** [comment]
> Try running with java command line parameter "-verbose:class" - in my case it was an old version of Wildfly app server, whick was loading an old jackson-databind jar file

Works! Thanks!
