### ISSUE TITLE
No method or field found with any of the following signatures

### ISSUE THREAD

**Issue by HussarGnex** [graphql-java-kickstart/graphql-java-tools#287]
Hello!

I have a problem with field named quote. I have a method named getQuote in POJO but I'm getting this kind of error:

`  cloud.marciniak.blog.qutoes.resolvers.QuoteResolver.quote
  cloud.marciniak.blog.qutoes.models.Quote.quote()
  cloud.marciniak.blog.qutoes.models.Quote.getQuote()
  cloud.marciniak.blog.qutoes.models.Quote.quote
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	... 123 common frames omitted`

How I can fix that? Here is my repository with the whole code.
[Repository](https://github.com/HussarGnex/QuotesQL)

**Comment by oliemansm** [comment]
First param of that getQuote method should be the object you’re fetching it from, so in this case `Quote`. And seeing your schema the quote field in that object represents a String, so you should return that instead of Quote.

Which means you also don’t really need a separate resolver method for that field probably, but maybe you’re just experimenting a bit.

Make sure to look at the example project as well.

Groeten,
Michiel
________________________________
Van: Michał <notifications@github.com>
Verzonden: Tuesday, July 2, 2019 12:51:42 PM
Aan: graphql-java-kickstart/graphql-java-tools
CC: Subscribed
Onderwerp: [graphql-java-kickstart/graphql-java-tools] No method or field found with any of the following signatures (#287)


Hello!

I have a problem with field named quote. I have a method named getQuote in POJO but I'm getting this kind of error:

cloud.marciniak.blog.qutoes.resolvers.QuoteResolver.quote cloud.marciniak.blog.qutoes.models.Quote.quote() cloud.marciniak.blog.qutoes.models.Quote.getQuote() cloud.marciniak.blog.qutoes.models.Quote.quote at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE] at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE] ... 123 common frames omitted

How I can fix that? Here is my repository with the whole code.
https://github.com/HussarGnex/QuotesQL<Repository>

**Comment by HussarGnex** [comment]
Thanks for answer, but still I dont understand. In schema I have a type Quote with field named quote with type String and in Qoute.java I have method that returns field named quote - this method is called getQuote. When I remove getQuote() from schema (I was trying everything to make it work, that's why it's here) it should find getQoute() in Quote.java, right? When I do this I'm getting same problem. I'm really lost.

**Comment by oliemansm** [comment]
Yes, removing that resolver should work. What is the exact error you’re getting? Feels like you’ve only pasted part of the stacktrace

Groeten,
Michiel
________________________________
Van: Michał <notifications@github.com>
Verzonden: Tuesday, July 2, 2019 1:13:35 PM
Aan: graphql-java-kickstart/graphql-java-tools
CC: Michiel Oliemans; Comment
Onderwerp: Re: [graphql-java-kickstart/graphql-java-tools] No method or field found with any of the following signatures (#287)


Thanks for answer, but still I dont understand. In schema I have a type Quote with field named quote with type String and in Qoute.java I have method that returns field named quote - this method is called getQuote. When I remove getQuote() from schema (I was trying everything to make it work, that's why it's here) it should find getQoute() in Quote.java, right? When I do this I'm getting same problem. I'm really lost.

**Comment by HussarGnex** [comment]
Removing method form resolver and resolver from GraphqlConfiguration didn't helped. 
Here's full stacktrace:

`	at com.coxautodev.graphql.tools.SchemaParserBuilder.build(SchemaParserBuilder.kt:157) ~[graphql-java-tools-5.2.4.jar:na]
	at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration.schemaParser(GraphQLJavaToolsAutoConfiguration.java:57) ~[graphql-spring-boot-autoconfigure-5.0.2.jar:na]
	at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration$$EnhancerBySpringCGLIB$$1610e0a0.CGLIB$schemaParser$1(<generated>) ~[graphql-spring-boot-autoconfigure-5.0.2.jar:na]
	at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration$$EnhancerBySpringCGLIB$$1610e0a0$$FastClassBySpringCGLIB$$b8d91a76.invoke(<generated>) ~[graphql-spring-boot-autoconfigure-5.0.2.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
ConfigurationClassEnhancer.java:363
	at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration$$EnhancerBySpringCGLIB$$1610e0a0.schemaParser(<generated>) ~[graphql-spring-boot-autoconfigure-5.0.2.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
Method.java:498
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	... 124 common frames omitted`

**Comment by oliemansm** [comment]
That’s not the full stack trace, missing the top line.

Groeten,
Michiel
________________________________
Van: Michał <notifications@github.com>
Verzonden: Tuesday, July 2, 2019 1:54:49 PM
Aan: graphql-java-kickstart/graphql-java-tools
CC: Michiel Oliemans; Comment
Onderwerp: Re: [graphql-java-kickstart/graphql-java-tools] No method or field found with any of the following signatures (#287)


Removing method form resolver and resolver from GraphqlConfiguration didn't helped.
Here's full stacktrace:

at com.coxautodev.graphql.tools.SchemaParserBuilder.build(SchemaParserBuilder.kt:157) ~[graphql-java-tools-5.2.4.jar:na] at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration.schemaParser(GraphQLJavaToolsAutoConfiguration.java:57) ~[graphql-spring-boot-autoconfigure-5.0.2.jar:na] at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration$$EnhancerBySpringCGLIB$$1610e0a0.CGLIB$schemaParser$1(<generated>) ~[graphql-spring-boot-autoconfigure-5.0.2.jar:na] at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration$$EnhancerBySpringCGLIB$$1610e0a0$$FastClassBySpringCGLIB$$b8d91a76.invoke(<generated>) ~[graphql-spring-boot-autoconfigure-5.0.2.jar:na] at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.1.8.RELEASE.jar:5.1.8.RELEASE] at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE] ConfigurationClassEnhancer.java:363 at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration$$EnhancerBySpringCGLIB$$1610e0a0.schemaParser(<generated>) ~[graphql-spring-boot-autoconfigure-5.0.2.jar:na] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191] at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191] Method.java:498 at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE] ... 124 common frames omitted

**Comment by HussarGnex** [comment]
On pastebin I pasted full stacktrace from debug console in VSCode.
Here I pasted it again - https://pastebin.com/jeVfZiH3

**Comment by oliemansm** [comment]
The stack trace still shows that it’s looking for the getQuote(Quote) method on your QuoteResolver. Apparently the QuoteResolver is still passed to graphql-java-tools, otherwise it wouldn’t be complaining about it

Groeten,
Michiel
________________________________
Van: Michał <notifications@github.com>
Verzonden: Tuesday, July 2, 2019 3:01:10 PM
Aan: graphql-java-kickstart/graphql-java-tools
CC: Michiel Oliemans; Comment
Onderwerp: Re: [graphql-java-kickstart/graphql-java-tools] No method or field found with any of the following signatures (#287)


On pastebin I pasted full stacktrace from debug console in VSCode.
Here I pasted it again - https://pastebin.com/jeVfZiH3

**Comment by HussarGnex** [comment]
I will try later to create this project from scratch, because right now I deleted the resolver and bean in GraphqlConfiguration but still I'm getting this same problem. Please don't close this topic, today/tomorrow I'll let you know if it helped.

**Comment by HussarGnex** [comment]
After creating new project I've got the same problem. Deleted resolver and it's bean. Still getting
`Factory method 'schemaParser' threw exception; nested exception is com.coxautodev.graphql.tools.FieldResolverError: No method or field found with any of the following signatures (with or without one of [interface graphql.schema.DataFetchingEnvironment] as the last argument), in priority order:

  cloud.marciniak.graphql.Quotes.models.Quote.quote()
  cloud.marciniak.graphql.Quotes.models.Quote.getQuote()
  cloud.marciniak.graphql.Quotes.models.Quote.quote`
When this model have that method. Damn it.

**Comment by oliemansm** [comment]
First of all: you're working with very outdated versions of these libs. Make sure to upgrade to the latest versions. And you don't have to explicitly import `graphql-java-tools`. That's pulled in by `graphql-spring-boot`. And mind the groupId which has been changed. So in your case the relevant section in your pom should be updated to:
```xml
<dependency>
			<groupId>com.graphql-java-kickstart</groupId>
			<artifactId>graphql-spring-boot-starter</artifactId>
			<version>5.10.0</version>
		</dependency>
		<dependency>
			<groupId>com.graphql-java-kickstart</groupId>
			<artifactId>graphiql-spring-boot-starter</artifactId>
			<version>5.10.0</version>
		</dependency>
```
And secondly to fix your issue: you have misspelled `quote` in your class as `qoute`. So the field does in fact not exist in the class and therefore graphql correctly throws an exception that it can't find the field you specified.
