### ISSUE TITLE
Version 5.6.1 silently upgraded to graphql-java 13

### ISSUE THREAD

**Issue by lqc** [graphql-java-kickstart/graphql-java-tools#299]
The release page did not mentioned this and when trying to use the library with graphql-java 12, it fails with

```
java.lang.NoSuchMethodError: graphql.language.Directive.<init>(Ljava/lang/String;Ljava/util/List;Lgraphql/language/SourceLocation;Ljava/util/List;Lgraphql/language/IgnoredChars;Ljava/util/Map;)V
	at com.coxautodev.graphql.tools.relay.RelayConnectionFactory$DirectiveWithField.<init>(RelayConnectionFactory.kt:91) ~[graphql-java-tools-5.6.1.jar:na]
	at com.coxautodev.graphql.tools.relay.RelayConnectionFactory.withField(RelayConnectionFactory.kt:84) ~[graphql-java-tools-5.6.1.jar:na]
	at com.coxautodev.graphql.tools.relay.RelayConnectionFactory.directivesWithField(RelayConnectionFactory.kt:88) ~[graphql-java-tools-5.6.1.jar:na]
	at com.coxautodev.graphql.tools.relay.RelayConnectionFactory.findConnectionDirectives(RelayConnectionFactory.kt:45) ~[graphql-java-tools-5.6.1.jar:na]
	at com.coxautodev.graphql.tools.relay.RelayConnectionFactory.create(RelayConnectionFactory.kt:26) ~[graphql-java-tools-5.6.1.jar:na]
```

Not something that can be really fixed now, but maybe someone runs into a similar issue. Would appreciate if didn't make such breaking changes in a patch releases ;).

**Comment by oliemansm** [comment]
Thanks for pointing it out, updated the release notes.
