### ISSUE TITLE
No method or field found as defined in schema <unknown>:49 with any of the following signatures

### ISSUE THREAD

**Issue by hzariv** [graphql-java-kickstart/graphql-java-tools#307]
I have the following type in my schema but it seems like FieldResolver is trying to find text field in java.lang.String for some unknown reason. I am using the following artifact version:

```xml
 <groupId>com.graphql-java-kickstart</groupId>
 <artifactId>graphql-java-tools</artifactId>
 <version>5.6.1</version>
```

```graphql
type TextSpan {
    text : String
    styles : [StyleEnum]
    template : String
    accessibilityText : String
    icon : String
    tooltip : String
}
```

```
Caused by: com.coxautodev.graphql.tools.FieldResolverError: No method or field found as defined in schema <unknown>:49 with any of the following signatures (with or without one of [interface graphql.schema.DataFetchingEnvironment] as the last argument), in priority order:

  java.lang.String.text()
  java.lang.String.getText()
  java.lang.String.text
	at com.coxautodev.graphql.tools.FieldResolverScanner.missingFieldResolver(FieldResolverScanner.kt:59)
	at com.coxautodev.graphql.tools.FieldResolverScanner.findFieldResolver(FieldResolverScanner.kt:50)
	at com.coxautodev.graphql.tools.SchemaClassScanner.scanResolverInfoForPotentialMatches(SchemaClassScanner.kt:257)
	at com.coxautodev.graphql.tools.SchemaClassScanner.scanQueueItemForPotentialMatches(SchemaClassScanner.kt:251)
	at com.coxautodev.graphql.tools.SchemaClassScanner.scanQueue(SchemaClassScanner.kt:103)
	at com.coxautodev.graphql.tools.SchemaClassScanner.scanForClasses(SchemaClassScanner.kt:81)
	at com.coxautodev.graphql.tools.SchemaParserBuilder.scan(SchemaParserBuilder.kt:165)
	at com.coxautodev.graphql.tools.SchemaParserBuilder.build(SchemaParserBuilder.kt:206)
	at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration.schemaParser(GraphQLJavaToolsAutoConfiguration.java:98)
	at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration$$EnhancerBySpringCGLIB$$1b3edc9f.CGLIB$schemaParser$1(<generated>)
	at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration$$EnhancerBySpringCGLIB$$1b3edc9f$$FastClassBySpringCGLIB$$d6c01f07.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
	at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration$$EnhancerBySpringCGLIB$$1b3edc9f.schemaParser(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 140 common frames omitted
```

**Comment by vojtapol** [comment]
This means that the scanner bound Java's `String` to GraphQL's `TextSpan` already at this point. This can happen for various reasons but mostly likely you have something like this:

```graphql
extend type Query {
  getSpan: TextSpan
}
```

```java
public String getSpan() {
...
}
```

**Comment by lisensaka** [comment]
this error is thrown while the application is trying to wire the Schema fields with the Java Object that you have declared for binding, the Java Object fields should have the exact same name as the Schema field names otherwise it will throw the FieldResolverError.
in this case you have a mismatch of the Schema field called "text" and the Java Object  field "text", this should have the exact same name like below:

Schema: 

type TextSpan {
    text : String
.....
    }

Java Object:

class Example {
String text;
......
}
