### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: graphql.schema.GraphQLCodeRegistry

### ISSUE THREAD

**Issue by jyjyj** [graphql-java-kickstart/graphql-java-tools#402]
Hi, I'm trying to move away from implementing DataFetchers and using RuntimeWiring as in the graphql-java tutorials, and trying to build the executableSchema with references to my own resolvers etc. I'm using `id 'org.springframework.boot' version '2.2.2.RELEASE'` and have the following Builder class:

```
package test.main;

import graphql.GraphQL;
import graphql.kickstart.tools.GraphQLResolver;
import graphql.kickstart.tools.SchemaParser;
import graphql.schema.GraphQLScalarType;
import graphql.schema.GraphQLSchema;
import java.util.Collection;
import java.util.List;
import java.util.regex.Pattern;

import javax.servlet.annotation.WebServlet;

import org.reflections.Reflections;
import org.reflections.scanners.ResourcesScanner;

@WebServlet(name = "HelloServlet", urlPatterns = {"graphql-v2/*"}, loadOnStartup = 1)
public class GraphQLBuilder {

    private static final String GRAPHQL_RESOURCES_PACKAGE = "graphql";

    private static final Pattern SCHEMAS_REGEX = Pattern.compile(".*\\.graphql");

    private final List<? extends GraphQLResolver<?>> resolvers;
    private final Collection<Class<?>> typeDictionary;
    private final List<GraphQLScalarType> scalars;

    public GraphQLBuilder(List<? extends GraphQLResolver<?>> resolvers, Collection<Class<?>> typeDictionary, List<GraphQLScalarType> scalars) {
        this.resolvers = resolvers;
        this.typeDictionary = typeDictionary;
        this.scalars = scalars;
    }

    public GraphQL createGraphQL() {
        return GraphQL.newGraphQL(parseSchemaFromResources()).build();
    }

    private GraphQLSchema parseSchemaFromResources() {
        return SchemaParser.newParser()
            .files(findSchemasFiles())
            .scalars(scalars)
            .resolvers(resolvers)
            .dictionary(typeDictionary)
            .build()
            .makeExecutableSchema();
    }

    private static String[] findSchemasFiles() {
        Reflections reflections = new Reflections(GRAPHQL_RESOURCES_PACKAGE, new ResourcesScanner());
        return reflections.getResources(SCHEMAS_REGEX).stream().sorted().toArray(String[]::new);
    }

//	@Override
//	protected GraphQLConfiguration getConfiguration() {
//		return GraphQLConfiguration.with(parseSchemaFromResources()).build();
//	}
}
```

and I'm calling it as:

```
List<GraphQLResolver<?>> resolvers = new ArrayList<GraphQLResolver<?>>();
resolvers.add(taskingQueryImplementation);
resolvers.add(taskingMutationImplementation);
resolvers.add(alertsQueryImplementation);
resolvers.add(alertsMutationImplementation);
List<GraphQLScalarType> scalars = new ArrayList<GraphQLScalarType>();
scalars.add(ExtendedScalars.DateTime);
this.graphQL = new GraphQLBuilder(resolvers, null, scalars).createGraphQL();
```

However, I'm getting a classnotfoundexception (as in the title of this issue) at the `.build()` step in the `parseSchemaFromResources()` function. Haven't been able to figure this out, and also don't know if it's a gradle clash issue, but the relevant parts of my gradle build are:

```
implementation 'com.graphql-java:graphql-java:11.0' // NEW
implementation 'com.graphql-java:graphql-java-spring-boot-starter-webmvc:1.0' // NEW
implementation 'com.google.guava:guava:26.0-jre' // NEW
implementation 'org.springframework.boot:spring-boot-starter-web'
testImplementation 'org.springframework.boot:spring-boot-starter-test'

compile 'com.graphql-java-kickstart:graphql-java-tools:6.0.2'
    
compileOnly "org.projectlombok:lombok:1.18.8"
annotationProcessor "org.projectlombok:lombok:1.18.8"
	
implementation 'org.json:json:20190722'
implementation 'org.apache.httpcomponents:httpclient:4.5.12'
implementation 'org.postgresql:postgresql:42.2.12'
    
// https://github.com/donbeave/graphql-java-datetime
implementation("com.zhokhov.graphql:graphql-datetime-spring-boot-starter:1.9.0")
    
// extended scalar if still using the classic graphql-java way
// https://github.com/graphql-java/graphql-java-extended-scalars
compile 'com.graphql-java:graphql-java-extended-scalars:1.0'

implementation 'org.reflections:reflections:0.9.12'
```

The version of `graphql-java-tools` that I use is above, but my error looks something like:

```
Caused by: java.lang.NoClassDefFoundError: graphql/schema/GraphQLCodeRegistry
	at graphql.kickstart.tools.SchemaParser.<init>(SchemaParser.kt:59) ~[graphql-java-tools-6.0.2.jar:na]
	at graphql.kickstart.tools.SchemaParserBuilder.build(SchemaParserBuilder.kt:207) ~[graphql-java-tools-6.0.2.jar:na]
	at aris.main.GraphQLBuilder.parseSchemaFromResources(GraphQLBuilder.java:47) ~[main/:na]
	at aris.main.GraphQLBuilder.createGraphQL(GraphQLBuilder.java:35) ~[main/:na]
	at aris.main.GraphQLProvider.init(GraphQLProvider.java:99) ~[main/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389) ~[spring-beans-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333) ~[spring-beans-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157) ~[spring-beans-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	... 18 common frames omitted
Caused by: java.lang.ClassNotFoundException: graphql.schema.GraphQLCodeRegistry
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[na:na]
	... 30 common frames omitted
```

Thank you!

**Comment by jyjyj** [comment]
Fixed by changing this part of my build.gradle file:

`
implementation 'com.graphql-java:graphql-java:11.0' // NEW`

to version 14.0

**Comment by vojtapol** [comment]
> Fixed by changing this part of my build.gradle file:
> 
> ` implementation 'com.graphql-java:graphql-java:11.0' // NEW`
> 
> to version 14.0

When using `graphql-java-tools` do *not* manually specify dependency on `graphql-java`. Instead, let `graphql-java-tools` pull the compatible version of `graphql-java` transitively.
