### ISSUE TITLE
Spring Boot and GraphQL: @Component issue 

### ISSUE THREAD

**Issue by Urunov** [graphql-java-kickstart/graphql-java-tools#449]
When I started Spring Boot and GraphQL API creating process I faced issue related to **Annotation.**  @Component. 
_There are 2 classes:  MutationResolver and QueryResolver .class_ 
RequiredArgsConstructor

**### QueryResolver .class_** 
```java
public class TotalQueryResolver implements GraphQLQueryResolver {

    private final CategoryRepository categoryRepository;
    public Iterable<Category> allCategories(){
        return categoryRepository.findAll();
    }
    public Category category(Integer id){
        return categoryRepository.findById(id).orElseGet(null);
    }
}
```

MutationResolver.class

```java
@Component
public class TotalMutationResolver implements GraphQLMutationResolver {

    @Autowired
    private CategoryRepository categoryRepository;

    public Category addCategory(String name) {

        Category category = new Category();
        category.setName(name);

        return categoryRepository.saveAndFlush(category);
    }

    public List<Category> allCategories(){

        return categoryRepository.findAll();
    }

    public Category updateCategory(Long id, String name){
        Category category = new Category();
        category.setCategory_id(id);
        category.setName(name);

        return categoryRepository.saveAndFlush(category);
    }


    public Boolean deleteCategory(Integer id){
        categoryRepository.deleteById(id);
        return true;
    }
}
```

-----------------
When I compile the source no any error, however in broweser. _(404 error)_
**Indeed, my schema.graphqls**

```graphql
         type Query  {
            allCategories: [Category]
            category(id: ID!): Category
      }  

       type Mutation {
         addCategory(name: String!): Category!
         updateCategory(id: ID!, name: String!): Category!
        deleteCategory(id: ID!): Boolean
      }
       type Category {
         id: ID
         name: String!
      }
```

In attachment figure, after adding @Component result; 

<img width="1391" alt="AnnotationError" src="https://user-images.githubusercontent.com/11626327/96073227-0341b380-0ee1-11eb-92a2-ad3c575ac4dd.png">

**Comment by vojtapol** [comment]
I don't understand what are you asking. Can you paste the original exception with the stack-trace here instead of a screenshot from IntelliJ?

**Comment by Urunov** [comment]
@vojtapol thank you for response. 

I attached here. Regarding issues in the code .
When I use @Component annotation class Resolver.

@RequiredArgsConstructor
@Component
public class TotalQueryResolver implements GraphQLQueryResolver {

    private final CategoryRepository categoryRepository;
    (same as before source code)
}
======

@Component
public class TotalMutationResolver implements GraphQLMutationResolver {

    @Autowired
    private CategoryRepository categoryRepository;
}

after compile my source code. >>>>>

------------------------------------------Console (IntelliJ)-----------------------------------------------------
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.coxautodev.graphql.tools.SchemaParser]: Factory method 'schemaParser' threw exception; nested exception is com.coxautodev.graphql.tools.FieldResolverError: No method or field found with any of the following signatures (with or without one of [interface graphql.schema.DataFetchingEnvironment] as the last argument), in priority order:

  com.urunov.entity.Category.id()
  com.urunov.entity.Category.getId()
  com.urunov.entity.Category.id
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:650) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	... 129 common frames omitted
Caused by: com.coxautodev.graphql.tools.FieldResolverError: No method or field found with any of the following signatures (with or without one of [interface graphql.schema.DataFetchingEnvironment] as the last argument), in priority order:

  com.urunov.entity.Category.id()
  com.urunov.entity.Category.getId()
  com.urunov.entity.Category.id
	at com.coxautodev.graphql.tools.FieldResolverScanner.missingFieldResolver(FieldResolverScanner.kt:51) ~[graphql-java-tools-5.2.4.jar:na]
	at com.coxautodev.graphql.tools.FieldResolverScanner.findFieldResolver(FieldResolverScanner.kt:42) ~[graphql-java-tools-5.2.4.jar:na]
	at com.coxautodev.graphql.tools.SchemaClassScanner.scanResolverInfoForPotentialMatches(SchemaClassScanner.kt:227) ~[graphql-java-tools-5.2.4.jar:na]
	at com.coxautodev.graphql.tools.SchemaClassScanner.scanQueueItemForPotentialMatches(SchemaClassScanner.kt:222) ~[graphql-java-tools-5.2.4.jar:na]
	at com.coxautodev.graphql.tools.SchemaClassScanner.scanQueue(SchemaClassScanner.kt:106) ~[graphql-java-tools-5.2.4.jar:na]
	at com.coxautodev.graphql.tools.SchemaClassScanner.scanForClasses(SchemaClassScanner.kt:84) ~[graphql-java-tools-5.2.4.jar:na]
	at com.coxautodev.graphql.tools.SchemaParserBuilder.scan(SchemaParserBuilder.kt:151) ~[graphql-java-tools-5.2.4.jar:na]
	at com.coxautodev.graphql.tools.SchemaParserBuilder.build(SchemaParserBuilder.kt:157) ~[graphql-java-tools-5.2.4.jar:na]
	at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration.schemaParser(GraphQLJavaToolsAutoConfiguration.java:57) ~[graphql-spring-boot-autoconfigure-5.0.2.jar:na]
	at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration$$EnhancerBySpringCGLIB$$791f9b41.CGLIB$schemaParser$1(<generated>) ~[graphql-spring-boot-autoconfigure-5.0.2.jar:na]
	at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration$$EnhancerBySpringCGLIB$$791f9b41$$FastClassBySpringCGLIB$$c9b88495.invoke(<generated>) ~[graphql-spring-boot-autoconfigure-5.0.2.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration$$EnhancerBySpringCGLIB$$791f9b41.schemaParser(<generated>) ~[graphql-spring-boot-autoconfigure-5.0.2.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	... 130 common frames omitted


Process finished with exit code 0
-----------------------------------------------------------------------------

**Comment by Urunov** [comment]
More .... source here.
https://github.com/Urunov/High-Performance-Java-Persistence/tree/master/Session-4.MappingGraphQLAPI

**Comment by Urunov** [comment]
@vojtapol 
thank u.
