### ISSUE TITLE
Compatibility with graphql-java 18

### ISSUE THREAD

**Issue by martinbonnin** [graphql-java-kickstart/graphql-java-tools#657]
Running against `graphql-java` 18 fails with 

```
java.lang.NoSuchMethodError: graphql.schema.GraphQLDirective$Builder.comparatorRegistry(Lgraphql/schema/GraphqlTypeComparatorRegistry;)Lgraphql/schema/GraphQLDirective$Builder;
	at graphql.kickstart.tools.SchemaParser.buildDirectives(SchemaParser.kt:309) ~[graphql-java-tools-12.0.2.jar:na]
	at graphql.kickstart.tools.SchemaParser.createObject(SchemaParser.kt:125) ~[graphql-java-tools-12.0.2.jar:na]
	at graphql.kickstart.tools.SchemaParser.parseSchemaObjects(SchemaParser.kt:81) ~[graphql-java-tools-12.0.2.jar:na]
```

See https://github.com/apollographql/federation-jvm/pull/171 for more context

**Comment by oryan-block** [comment]
Should be resolved now.
